from pysc2.lib import units

RESOLUTION = 200
THRESHOLD = int(RESOLUTION * 0.1)
STEP_MUL = 16
CAP_MINERALS = 400
CAP_GAS = 300

ATTACK_PRIORITY_GROUND = [units.Zerg.NydusCanal,
                          units.Zerg.LurkerBurrowed,
                          units.Zerg.Lurker,
                          units.Zerg.Ultralisk,
                          units.Zerg.Infestor,
                          units.Zerg.SwarmHost,
                          units.Zerg.Hydralisk,
                          units.Zerg.Ravager,
                          units.Zerg.Roach,
                          units.Zerg.Queen,
                          units.Zerg.SpineCrawler,
                          units.Zerg.SporeCrawler,
                          units.Zerg.Zergling,
                          units.Zerg.SpineCrawlerUprooted,
                          units.Zerg.SporeCrawlerUprooted,
                          units.Zerg.Drone,
                          units.Zerg.Baneling,
                          units.Zerg.CreepTumor,
                          units.Zerg.CreepTumorQueen,
                          units.Zerg.CreepTumorBurrowed,
                          units.Zerg.LurkerCocoon,
                          units.Zerg.RavagerCocoon,
                          units.Zerg.BanelingCocoon,
                          units.Zerg.GreaterSpire,
                          units.Zerg.Spire,
                          units.Zerg.UltraliskCavern,
                          units.Zerg.LurkerDen,
                          units.Zerg.HydraliskDen,
                          units.Zerg.RoachWarren,
                          units.Zerg.SpawningPool,
                          units.Zerg.EvolutionChamber,
                          units.Zerg.NydusNetwork,
                          units.Zerg.InfestationPit,
                          units.Zerg.BanelingNest,
                          units.Zerg.Hive,
                          units.Zerg.Lair,
                          units.Zerg.Hatchery,
                          units.Zerg.Extractor,
                          units.Zerg.ExtractorRich,

                          units.Protoss.DarkTemplar,
                          units.Protoss.Archon,
                          units.Protoss.HighTemplar,
                          units.Protoss.Disruptor,
                          units.Protoss.Colossus,
                          units.Protoss.Immortal,
                          units.Protoss.Zealot,
                          units.Protoss.Stalker,
                          units.Protoss.DisruptorPhased,
                          units.Protoss.Adept,
                          units.Protoss.PhotonCannon,
                          units.Protoss.Sentry,
                          units.Protoss.Probe,
                          units.Protoss.Pylon,
                          units.Protoss.ShieldBattery,
                          units.Protoss.PylonOvercharged,
                          units.Protoss.DarkShrine,
                          units.Protoss.FleetBeacon,
                          units.Protoss.TemplarArchive,
                          units.Protoss.TwilightCouncil,
                          units.Protoss.MothershipCore,
                          units.Protoss.Forge,
                          units.Protoss.WarpGate,
                          units.Protoss.Stargate,
                          units.Protoss.Gateway,
                          units.Protoss.RoboticsBay,
                          units.Protoss.RoboticsFacility,
                          units.Protoss.CyberneticsCore,
                          units.Protoss.Nexus,
                          units.Protoss.Assimilator,
                          units.Protoss.AssimilatorRich,

                          units.Terran.SiegeTankSieged,
                          units.Terran.Thor,
                          units.Terran.ThorHighImpactMode,
                          units.Terran.Ghost,
                          units.Terran.GhostAlternate,
                          units.Terran.GhostNova,
                          units.Terran.VikingAssault,
                          units.Terran.Hellbat,
                          units.Terran.Hellion,
                          units.Terran.Cyclone,
                          units.Terran.WidowMine,
                          units.Terran.WidowMineBurrowed,
                          units.Terran.Marauder,
                          units.Terran.Reaper,
                          units.Terran.Marine,
                          units.Terran.Bunker,
                          units.Terran.SiegeTank,
                          units.Terran.MissileTurret,
                          units.Terran.SCV,
                          units.Terran.Nuke,
                          units.Terran.SensorTower,
                          units.Terran.FusionCore,
                          units.Terran.GhostAcademy,
                          units.Terran.EngineeringBay,
                          units.Terran.Armory,
                          units.Terran.SupplyDepot,
                          units.Terran.SupplyDepotLowered,
                          units.Terran.PlanetaryFortress,
                          units.Terran.Starport,
                          units.Terran.Factory,
                          units.Terran.Barracks,
                          units.Terran.OrbitalCommand,
                          units.Terran.CommandCenter,
                          units.Terran.Refinery,
                          units.Terran.RefineryRich,
                          units.Terran.Reactor,
                          units.Terran.TechLab,
                          units.Terran.StarportReactor,
                          units.Terran.StarportTechLab,
                          units.Terran.FactoryReactor,
                          units.Terran.FactoryTechLab,
                          units.Terran.BarracksReactor,
                          units.Terran.BarracksTechLab]

ATTACK_PRIORITY_AIR = [units.Zerg.BroodLord,
                       units.Zerg.Mutalisk,
                       units.Zerg.Corruptor,
                       units.Zerg.Viper,
                       units.Zerg.OverlordTransport,
                       units.Zerg.Overseer,
                       units.Zerg.OverseerOversightMode,
                       units.Zerg.BroodLordCocoon,
                       units.Zerg.OverlordTransportCocoon,
                       units.Zerg.OverseerCocoon,
                       units.Zerg.Overlord,

                       units.Protoss.Carrier,
                       units.Protoss.Mothership,
                       units.Protoss.VoidRay,
                       units.Protoss.Tempest,
                       units.Protoss.WarpPrism,
                       units.Protoss.WarpPrismPhasing,
                       units.Protoss.Oracle,
                       units.Protoss.Phoenix,
                       units.Protoss.Observer,
                       units.Protoss.ObserverSurveillanceMode,

                       units.Terran.Battlecruiser,
                       units.Terran.LiberatorAG,
                       units.Terran.Liberator,
                       units.Terran.Raven,
                       units.Terran.Banshee,
                       units.Terran.VikingFighter,
                       units.Terran.Medivac,
                       units.Terran.StarportFlying,
                       units.Terran.FactoryFlying,
                       units.Terran.BarracksFlying,
                       units.Terran.OrbitalCommandFlying,
                       units.Terran.CommandCenterFlying]

ATTACK_PRIORITY_ALL = ATTACK_PRIORITY_AIR + ATTACK_PRIORITY_GROUND
ATTACK_PRIORITY_GROUND = {key: len(ATTACK_PRIORITY_GROUND) - i
                          for i, key in enumerate(ATTACK_PRIORITY_GROUND)}
ATTACK_PRIORITY_AIR = {key: len(ATTACK_PRIORITY_AIR) - i
                       for i, key in enumerate(ATTACK_PRIORITY_AIR)}
ATTACK_PRIORITY_ALL = {key: len(ATTACK_PRIORITY_ALL) - i
                       for i, key in enumerate(ATTACK_PRIORITY_ALL)}
ATTACK_PRIORITY = {'Ground': ATTACK_PRIORITY_GROUND,
                   'Air': ATTACK_PRIORITY_AIR,
                   'All': ATTACK_PRIORITY_ALL}
